# Generated by Django 4.1.3 on 2023-06-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactus',
        ),
    ]
