# Generated by Django 4.1.3 on 2023-06-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'پیام ', 'verbose_name_plural': 'پیام ها'},
        ),
    ]
