# Generated by Django 4.1.3 on 2023-06-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='passgenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=15)),
                ('lowercase', models.CharField(max_length=15)),
                ('lettercase', models.CharField(max_length=15)),
            ],
        ),
    ]
