# Generated by Django 4.1.3 on 2023-06-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passgenerator',
            name='symbols',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='passgenerator',
            name='number',
            field=models.IntegerField(),
        ),
    ]
